### ISSUE TITLE
Get "undefined method" when logstash is not running

### ISSUE THREAD

**Issue by MarcusCaepio** [widhalmt/check_logstash#21]
Hi Thomas,
just checked the latest version of the script on my local machine (Ubuntu 16.04.3).
When logstash is not running, I get a undefined error method from the script:
./check_logstash.rb -H 1.2.3.4
./check_logstash.rb:207:in `fetch': undefined method `critical' for CheckLogstash::Fetcher:Module (NoMethodError)
        from ./check_logstash.rb:312:in `fetch'
        from ./check_logstash.rb:78:in `run'
        from ./check_logstash.rb:435:in `<main>'

**Comment by widhalmt** [comment]
Yes, this is all but nice, you're right. I'll add a nicer output.
