### ISSUE TITLE
inflight_events_main shows negative vlaue

### ISSUE THREAD

**Issue by MarcusCaepio** [widhalmt/check_logstash#28]
Hi,
I am getting several thousand events over logstash. The input shows me a negative value, what seems to be a bug.
Plugin Output
CRITICAL - Logstash is unhealthy - CRITICAL: Inflight events: main: -125;

**Comment by widhalmt** [comment]
Yes, that's a bug. It seems, Logstash is rotating the count now and then. We should definitely take care of that.

**Comment by MarcusCaepio** [comment]
Tested the last release, still negative values and so, unusablefor me :(

**Comment by widhalmt** [comment]
Ok, I'm sorry. I'll have a look, soon.

**Comment by MarcusCaepio** [comment]
Thanks a lot :)
